apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: datastore
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: datastore
    spec:
      containers:
      - name: datastore
        image: localhost:5000/datastore
        imagePullPolicy: IfNotPresent
