apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:dev"
  artifacts:
  - imageName: done/pubsub
    docker:
      dockerfilePath: gcp/DockerfilePubSub
  - imageName: done/datastore
    docker:
      dockerfilePath: gcp/DockerfileDataStore
deploy:
  kubectl:
    manifests:
      - kubernetes/datastore.yaml
      - kubernetes/pubsub.yaml
